### ISSUE TITLE
Increasing coverage of tests

### ISSUE THREAD

**Issue by matt-graham** [baxmittens/DistributedSparseGrids.jl#11]
Raising issue as part of JOSS review https://github.com/openjournals/joss-reviews/issues/5003

As discussed in #10 current there is only a single test in the automated test suite in `test/runtests.jl` which checks whether the output of the `integrate` function on an adaptively refined sparse grid for a particular test function is close to a reference value. 

While this is a useful test, ideally we would have tests covering more cases of this task (as detailed in #10) but also more granular unit tests of all the methods / types exposed by the API, and also similar integration tests checking the values computed by `interpolate` against reference values.

**Comment by baxmittens** [comment]
I've added some more tests.

Testing only integration is fine, though. For the initialization of weights, interpolation is called since for the calculation of the weights the interpolator of the underlying level is used.

**Comment by matt-graham** [comment]
Okay that makes sese with regards to interpolation versus integration. Thanks for adding the additional tests
