### ISSUE TITLE
joss-paper: Add contribution guidelines

### ISSUE THREAD

**Issue by ericneiva** [baxmittens/DistributedSparseGrids.jl#5]
@baxmittens, could you please add contribution guidelines for third-parties wishing to:

* Contribute to the software
* Report issues or problems with the software, or
* Seek support

When you add them, please verify they are linked [here](https://github.com/baxmittens/DistributedSparseGrids.jl/community).

See openjournals/joss-reviews#5003

**Comment by baxmittens** [comment]
should be all fine now. I close this issue. if something is wrong or missing with my contribution guidelines, feel free to reopen.
