### ISSUE TITLE
joss-paper: Minor

### ISSUE THREAD

**Issue by ericneiva** [baxmittens/DistributedSparseGrids.jl#7]
### Core API documentation

* [x] Document `CollocationPoint`
* [x] Document `HierarchicalCollocationPoint`
* [x] [This signature](https://github.com/baxmittens/DistributedSparseGrids.jl/blob/76314b4a939858aa9c7c5c604d2ad4a4a3961542/src/DistributedSparseGrids.jl#L400) does not correspond to the function signature it documents

### Examples

[In this example](https://github.com/baxmittens/DistributedSparseGrids.jl#point-sets)

* [x] Should the first line of the code snippet read `using DistributedSparseGrids`
* [x] `pointprobs` argument of `sparse_grid`... would `pointprops` be a better name?

### Paper

* [x] I would recommend to make the example self-contained, that is, add the missing lines needed to generate Figure 1 (happy to see that too in the readme documentation)
* [x] I would add DOIs or arXiv links to all references
* [x] Has all financial support been properly acknowledged?
* [x] (Line 4) Complete full affiliation details
* [x] (Line 18) to be solve*d*
* [x] (Line 18) ...and, in addition, *if* the solution... (does this make sense?)
* [x] In the example, `#set of all collocation points` to `# set of all collocation points`

### Archive

* [x] Has the software been already archived?

### Unused type variables

* [x] I run your tests with Julia 1.8.3 and I got the following "unused type variable" warnings:

```
WARNING: method definition for next_level_pt_idx at /home/eric-neiva/.julia/packages/DistributedSparseGrids/F7UUX/src/CollocationPoints/one_dimensional_collocation_points.jl:60 declares type variable CT but does not use it.
WARNING: method definition for length at /home/eric-neiva/.julia/packages/DistributedSparseGrids/F7UUX/src/AdaptiveSparseGrids/utils.jl:130 declares type variable HCP but does not use it.
WARNING: method definition for init! at /home/eric-neiva/.julia/packages/DistributedSparseGrids/F7UUX/src/DistributedSparseGrids.jl:71 declares type variable F but does not use it.
WARNING: method definition for init at /home/eric-neiva/.julia/packages/DistributedSparseGrids/F7UUX/src/DistributedSparseGrids.jl:106 declares type variable F but does not use it.
```

See https://github.com/openjournals/joss-reviews/issues/5003

**Comment by baxmittens** [comment]
Thank you for your detailed notes. I think I did changed everything accordingly. If this review is finished I will issue a new version of this package (0.1.4) and archive this version. I think this will be the best way. Do you agree @ericneiva ?

**Comment by baxmittens** [comment]
I forgot to mention: there was no financial support for this project.

**Comment by baxmittens** [comment]
to see the changes according to the unused type warning you may have to checkout the newest commit 
```julia
]add DistributedSparseGrids#7be01c3
```
or wait till I have registered a new release

**Comment by ericneiva** [comment]
> If this review is finished I will issue a new version of this package (0.1.4) and archive this version. I think this will be the best way. Do you agree @ericneiva ?

Sure, @baxmittens!

* On commit 7be01c3 I am still getting the first warning about an unused variable in `next_level_pt_idx`.
* Have you thought about listing the affiliation of the second author as "Independent Researcher" instead of "None"? See [here](https://joss.readthedocs.io/en/latest/submitting.html?highlight=affiliation#example-paper-and-bibliography)

Feel free to close this issue whenever the SW is archived.

**Comment by baxmittens** [comment]
Ok, thank you. I probably missed something there. I will double-check the unused variable and fix this.

I just had a look at this thread.

https://github.com/openjournals/joss/issues/406

Probably outdated...
My colleague (who recently changed company) is checking with his employer about what affiliation he should use for this paper. so this will probably change again anyways.
